-- # More sensible options
-- set -g default-terminal "xterm-kitty" # Ensure true colors
-- set -g base-index 1
-- set -g renumber-windows on
-- set -g pane-base-index 1
-- set -g prefix C-w
-- set -g mouse on
--
-- # Statusline
-- set -g status-left " "
-- set -g window-status-separator " "
-- set -g window-status-format "#I #W "
-- set -g window-status-current-format " #W "
-- set -g status-right "  #H    #S "
-- set -g status-style "bg=default bold"
-- set -g status-justify left
--
-- # Keybindings
-- unbind C-b
-- bind C-w send-prefix
-- bind -n M-c command-prompt
-- bind -n M-r { source-file ~/.tmux.conf ; display "Changes applied" }
-- is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
--
-- ## Windows (tabs in vim)
-- bind -n M-t neww
-- bind -n M-h next
-- bind -n M-k prev
--
-- ## Panes (windows in vim)
-- ### Creation
-- bind -n M-v splitw -h -c "#{pane_current_path}"
-- bind -n M-x splitw -v -c "#{pane_current_path}"
-- bind -n M-q if-shell "$is_vim" "send M-q" "killp"
-- ### Navigation
-- bind -n M-m if-shell "$is_vim" "send M-m" { if -F "#{pane_at_left}" "" "selectp -L" }
-- bind -n M-n if-shell "$is_vim" "send M-n" { if -F "#{pane_at_bottom}" "" "selectp -D" }
-- bind -n M-e if-shell "$is_vim" "send M-e" { if -F "#{pane_at_top}" "" "selectp -U" }
-- bind -n M-o if-shell "$is_vim" "send M-o" { if -F "#{pane_at_right}" "" "selectp -R" }
-- bind -T copy-mode-vi "M-m" if -F "#{pane_at_left}" "" "selectp -L"
-- bind -T copy-mode-vi "M-n" if -F "#{pane_at_bottom}" "" "selectp -D"
-- bind -T copy-mode-vi "M-e" if -F "#{pane_at_top}" "" "selectp -U"
-- bind -T copy-mode-vi "M-o" if -F "#{pane_at_right}" "" "selectp -R"
-- bind -n M-z if-shell "$is_vim" "resizep -Z ; send M-z" "resizep -Z"
-- ### Resize
-- bind -n C-M-m if-shell "$is_vim" "send C-M-m" "resizep -L 1"
-- bind -n C-M-n if-shell "$is_vim" "send C-M-n" "resizep -D 1"
-- bind -n C-M-e if-shell "$is_vim" "send C-M-e" "resizep -U 1"
-- bind -n C-M-o if-shell "$is_vim" "send C-M-o" "resizep -R 1"
-- bind -T copy-mode-vi C-M-m resizep -L 1
-- bind -T copy-mode-vi C-M-n resizep -D 1
-- bind -T copy-mode-vi C-M-e resizep -U 1
-- bind -T copy-mode-vi C-M-o resizep -R 1
--
-- ## Copy mode
-- setw -g mode-keys vi
-- bind -n M-y copy-mode
-- ### Commands
-- bind -T copy-mode-vi v send -X start-selection
-- bind -T copy-mode-vi V { send -X back-to-indentation ; send v ; send -X end-of-line }
-- bind -T copy-mode-vi l send -X other-end
-- bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -in -selection clipboard"
-- bind -n M-p paste
-- ### Movement
-- bind -T copy-mode-vi m send -X cursor-left
-- bind -T copy-mode-vi n send -X cursor-down
-- bind -T copy-mode-vi e send -X cursor-up
-- bind -T copy-mode-vi o send -X cursor-right
-- bind -T copy-mode-vi v send -X begin-selection
-- bind -T copy-mode-vi M send -X back-to-indentation
-- bind -T copy-mode-vi N send -X halfpage-down
-- bind -T copy-mode-vi E send -X halfpage-up
-- bind -T copy-mode-vi O send -X end-of-line
-- bind -T copy-mode-vi k send -X previous-word
-- bind -T copy-mode-vi K send -X previous-space
-- bind -T copy-mode-vi h send -X next-word
-- bind -T copy-mode-vi H send -X next-space
-- bind -T copy-mode-vi w send -X next-word-end
-- bind -T copy-mode-vi W send -X next-space-end
return {}
