return {
  keys = {
    ['<F9>'] = 'Hello',
    -- nox
    n = 'Next line',
    N = 'Next page',
    e = 'prEv line',
    E = 'prEv page',
    k = 'bacK word',
    K = 'bacK w.ord',
    w = 'rest of Word',
    W = 'rest of W.ord',
    h = 'Hop to next word',
    H = 'Hop to next w.ord',
    m = 'Move left',
    M = 'HoMe',
    o = 'Move right',
    O = 'eoL',
    ['\\'] = 'Next match',
    ['<tab>'] = 'Escape to normal mode',
    [',h'] = 'Add argument',
    ['do'] = 'Delete one',
    ss = 'Replace',
    f = 'Find in screen',
    F = 'Find in document',
    r = 'Remote',
    R = 'Repeat macro',
    v = 'Visual mode',
    t = 'To',
    T = 'back To',
    yd = 'Go to Declaration',
    yD = 'Go to Type',
    yr = 'Go to References',
    yI = 'Go to Implementation',
    cr = 'Code Rename',
    cs = 'Code Suggestions',
    cf = 'Code Format',
    cd = 'Code Definition',
    x = 'Next dx',
    X = 'Prev dx',
    gh = 'next Hunk',
    gH = 'last Hunk',
    gk = 'prev hunK',
    gK = 'first hunK',
    gs = 'Stage hunk',
    gS = 'Stage buffer',
    gr = 'Reset hunk',
    gR = 'Reset buffer',
    gu = 'Undo stage hunk',
    gp = 'Preview hunk inline',
    gb = 'Blame line',
    gB = 'Blame buffer',
    ['|'] = 'diff this',
    ['g|'] = 'diff this ~',
    ih = 'inner Hunk',

    -- nx
    s = 'Substitute',
    ['<cr>'] = 'Command line mode',

    -- n
    Y = 'Yank line',
    yy = 'Yank to eol',
    yp = 'Copy down',
    U = 'Unundo',
    [','] = 'Comma with auto undo breakpoints',
    [',,'] = 'Insert comma at the end',
    [';'] = {
      normal = 'Insert semicolon at the end',
      insert = 'Semicolon with auto undo breakpoints',
    },
    [',d'] = 'Delete comma or semicolon at the end',
    J = 'Join/Merge lines (pretty)',
    gJ = 'Join/Merge lines (raw)',
    i = 'Insert mode',
    D = 'Delete line',
    ['>'] = 'Indent',
    ['<'] = 'Deindent',
    l = 'Open Line below',
    L = 'Open Line above',

    -- x
    y = 'Yank',

    p = 'Paste',
    u = 'nop',
    ['`'] = 'Uppercase',
    ['~'] = 'Lowercase',
    V = 'Change visual mode',
    ['.'] = 'Dot with auto undo breakpoints',
  },
  control = {
    a = 'Add',
    x = 'Xtract',
    u = 'Undo jump',
    r = 'Toggle macro recording',
    s = 'Signature',
    y = 'Yes',
  },
  leader = {
    w = 'Harpoon 1',
    f = 'Harpoon 2',
    p = 'Harpoon 3',
    b = 'Harpoon 4',
    j = 'Harpoon 5',
    h = 'Harpoon menu',
    l = 'add Line below',
    ah = 'Harpoon add',
    aw = 'Harpoon add to 1',
    af = 'Harpoon add to 2',
    ap = 'Harpoon add to 3',
    ab = 'Harpoon add to 4',
    aj = 'Harpoon add to 5',
    L = 'add Line above',
    _ = 'Move window to bottom',
    ['|'] = 'Move window to rightmost side',
    ['='] = 'Evenly distributed windows',
    ['<c-a>'] = 'dynamic Add',
    ['<c-x>'] = 'dynamic Xtract',
  },
  alt = {
    q = 'Quit',
    n = 'Move line down',
    e = 'Move line up',
  },
}
