return {
  {
    "booperlv/nvim-gomove",
    opts = { map_defaults = false },
    keys = {
      { desc = "Move line up",          "<C-s>",      "<Plug>GoNSMUp" },
      { desc = "Move line down",        "<C-c>",      "<Plug>GoNSMDown" },
      { desc = "Move character left",   "<C-r>",      "<Plug>GoNSMLeft" },
      { desc = "Move character right",  "<C-d>",      "<Plug>GoNSMRight" },
      { desc = "Copy line up",          "<C-M-s>",    "<Plug>GoNSDUp" },
      { desc = "Copy line down",        "<C-M-c>",    "<Plug>GoNSDDown" },
      { desc = "Copy character left",   "<C-M-r>",    "<Plug>GoNSDLeft" },
      { desc = "Copy character right",  "<C-M-d>",    "<Plug>GoNSDRight" },
      { desc = "EoL paste correction",  "gp",         [[gv$2hoh<Plug>GoVSMRight]] },
      { desc = "Move selection down",   "<C-s>",      "<Plug>GoVSMUp",                  mode = "x" },
      { desc = "Move selection up",     "<C-c>",      "<Plug>GoVSMDown",                mode = "x" },
      { desc = "Move selection left",   "<C-r>",      "<Plug>GoVSMLeft",                mode = "x" },
      { desc = "Move selection right",  "<C-d>",      "<Plug>GoVSMRight",               mode = "x" },
      { desc = "Copy selection up",     "<C-M-s>",    "<Plug>GoVSDUp",                  mode = "x" },
      { desc = "Copy selection down",   "<C-M-c>",    "<Plug>GoVSDDown",                mode = "x" },
      { desc = "Copy selection left",   "<C-M-r>",    "<Plug>GoVSDLeft",                mode = "x" },
      { desc = "Copy selection right",  "<C-M-d>",    "<Plug>GoVSDRight",               mode = "x" },
      { desc = "EoL paste",             "gp",         [["_dpgv$hoh<Plug>GoVSMRight]],   mode = "x" },
      { desc = "EoL paste (clipboard)", "<leader>gp", [["_d"+pgv$hoh<Plug>GoVSMRight]], mode = "x" },
      { desc = "Move line down",        "<C-c>",      "<Esc><Plug>GoNSMDown gi",        mode = "i" },
      { desc = "Move line up",          "<C-s>",      "<Esc><Plug>GoNSMUp gi",          mode = "i" },
    },
  },
  {
    "tommcdo/vim-exchange",
    event = "VeryLazy",
  },
  {
    "junegunn/vim-easy-align",
    event = "VeryLazy",
    keys = {
      { desc = "Get aligned", "ga", "<Plug>(EasyAlign)", mode = { "n", "x" } },
    },
  },
}
